"""new tbl

Revision ID: 094047f4c08c
Revises: 6326e73641da
Create Date: 2023-08-18 11:40:11.022555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094047f4c08c'
down_revision = '6326e73641da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.Text(), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msg')
    # ### end Alembic commands ###
