"""req change approval

Revision ID: 125150ce8405
Revises: a98225f5895b
Create Date: 2023-07-31 15:01:18.797688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125150ce8405'
down_revision = 'a98225f5895b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('approval')

    # ### end Alembic commands ###
