"""Add new

Revision ID: 286035e1a10a
Revises: d14a1d11b8cb
Create Date: 2023-07-31 11:56:03.553039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286035e1a10a'
down_revision = 'd14a1d11b8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
