"""Add attendance column to User table

Revision ID: 79bb83edfd16
Revises: 
Create Date: 2023-07-20 15:13:05.466599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bb83edfd16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    op.add_column('user', sa.Column('attendance', sa.Text))

    # ### commands auto generated by Alembic - please adjust! ###


    # ### end Alembic commands ###
