"""Add new columns and create Requests table

Revision ID: d14a1d11b8cb
Revises: 79bb83edfd16
Create Date: 2023-07-24 13:38:25.468896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14a1d11b8cb'
down_revision = '79bb83edfd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.Integer(), nullable=False),
    sa.Column('request_tag', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sender', 'receiver')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_proof', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('identity_proof', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('other_documents', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('basic_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dearance_allowance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('house_rent_allowance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conveyance_allowance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manager', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('manager')
        batch_op.drop_column('conveyance_allowance')
        batch_op.drop_column('house_rent_allowance')
        batch_op.drop_column('dearance_allowance')
        batch_op.drop_column('basic_salary')
        batch_op.drop_column('other_documents')
        batch_op.drop_column('identity_proof')
        batch_op.drop_column('address_proof')
        batch_op.drop_column('address')
        batch_op.drop_column('designation')

    op.drop_table('requests')
    # ### end Alembic commands ###
